export const diseases = [
  {
    id: 'healthy',
    name: 'Healthy',
    scientific: 'No disease detected',
    tone: 'healthy',
    summary: 'The leaf shows no strong visual indicators of the diseases recognized by the model.',
    symptoms: ['Even green coloration', 'Intact leaf surface', 'No expanding streaks or lesions'],
    management: 'Continue routine monitoring and maintain balanced irrigation and nutrition.',
  },
  {
    id: 'black-sigatoka',
    name: 'Black Sigatoka',
    scientific: 'Pseudocercospora fijiensis',
    tone: 'critical',
    summary: 'A fungal leaf spot disease that reduces photosynthetic area and can cause major yield loss.',
    symptoms: ['Narrow reddish-brown streaks', 'Dark elongated lesions', 'Yellowing around affected tissue'],
    management: 'Remove heavily infected leaves, improve airflow, and consult local agricultural guidance before fungicide use.',
  },
  {
    id: 'yellow-sigatoka',
    name: 'Yellow Sigatoka',
    scientific: 'Pseudocercospora musae',
    tone: 'warning',
    summary: 'A fungal disease that develops from pale streaks into necrotic leaf spots.',
    symptoms: ['Pale yellow streaks', 'Brown oval spots', 'Premature leaf drying'],
    management: 'Prune infected material, reduce leaf wetness, and maintain recommended plant spacing.',
  },
  {
    id: 'fusarium-wilt',
    name: 'Fusarium Wilt',
    scientific: 'Fusarium oxysporum f. sp. cubense',
    tone: 'critical',
    summary: 'A persistent soil-borne vascular disease that causes yellowing and plant collapse.',
    symptoms: ['Older leaves yellow first', 'Leaf margins wilt', 'Pseudostem vascular discoloration'],
    management: 'Isolate the plant, disinfect tools, avoid moving contaminated soil, and notify local crop authorities.',
  },
  {
    id: 'bunchy-top',
    name: 'Banana Bunchy Top',
    scientific: 'Banana bunchy top virus',
    tone: 'warning',
    summary: 'A viral disease spread by banana aphids that produces narrow, upright, clustered leaves.',
    symptoms: ['Dark green dot-dash veins', 'Short narrow leaves', 'Bunched upright crown'],
    management: 'Do not propagate affected plants. Remove infected mats under local guidance and control aphid vectors.',
  },
];

export const seedDiagnoses = [
  {
    id: 'DX-1048',
    diseaseId: 'black-sigatoka',
    confidence: 94.2,
    latency: 84,
    date: '2026-08-12T08:42:00',
    location: 'Plot 4, Davao del Norte',
    source: 'Mobile',
    synced: true,
    model: 'EMV3-INT8 v1.4',
    image: '/assets/black-sigatoka-sample.png',
  },
  {
    id: 'DX-1047',
    diseaseId: 'healthy',
    confidence: 97.6,
    latency: 71,
    date: '2026-08-11T15:18:00',
    location: 'Plot 2, Davao del Norte',
    source: 'Mobile',
    synced: true,
    model: 'EMV3-INT8 v1.4',
    image: null,
  },
  {
    id: 'DX-1046',
    diseaseId: 'yellow-sigatoka',
    confidence: 89.8,
    latency: 92,
    date: '2026-08-10T10:06:00',
    location: 'Research greenhouse',
    source: 'Web',
    synced: true,
    model: 'EMV3-FP32 v1.4',
    image: null,
  },
  {
    id: 'DX-1045',
    diseaseId: 'bunchy-top',
    confidence: 86.4,
    latency: 79,
    date: '2026-08-09T07:31:00',
    location: 'Plot 1, Davao del Norte',
    source: 'Mobile',
    synced: true,
    model: 'EMV3-INT8 v1.4',
    image: null,
  },
];

export const getDisease = (id) => diseases.find((disease) => disease.id === id) ?? diseases[0];
