<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Article extends Model
{
    public const STATUS_DRAFT = 'draft';

    public const STATUS_PUBLISHED = 'published';

    public const TOPICS = ['field_care', 'prevention', 'treatment', 'varieties', 'identification', 'safety', 'research'];

    public const DISEASE_KEYS = ['healthy', 'sigatoka', 'panama-disease', 'cordana-leaf-spot'];

    public const IMAGE_DIRECTORY = 'article-images';

    /** Article photo names are generated by the server (or seeded): lowercase words, .webp only. */
    public const IMAGE_FILE_PATTERN = '/^[a-z0-9][a-z0-9-]{0,120}\.webp$/';

    protected $fillable = ['slug', 'title', 'disease_key', 'topic', 'language', 'summary', 'body', 'images', 'authors', 'status', 'published_at', 'created_by', 'updated_by'];

    protected function casts(): array
    {
        return ['published_at' => 'datetime', 'images' => 'array'];
    }

    public function sources(): BelongsToMany
    {
        return $this->belongsToMany(ResearchSource::class, 'article_research_source')
            ->withPivot('sort_order')
            ->orderBy('article_research_source.sort_order');
    }

    public function scopePublished(Builder $query): Builder
    {
        return $query->where('status', self::STATUS_PUBLISHED);
    }

    /** About 200 words a minute, at least one minute. */
    public function readingMinutes(): int
    {
        $text = preg_replace('/^\[\[image:[^\]]*\]\]$/m', '', $this->body);

        return max(1, (int) round(str_word_count(strip_tags($text)) / 200));
    }
}
