import { useCallback, useEffect, useMemo, useState } from 'react';
import {
  ActivityIndicator, Alert, Image, Modal, Platform, Pressable, SafeAreaView, ScrollView,
  StatusBar as NativeStatusBar, StyleSheet, Text, TextInput, View,
} from 'react-native';
import { StatusBar } from 'expo-status-bar';
import * as ImagePicker from 'expo-image-picker';
import NetInfo from '@react-native-community/netinfo';
import { Ionicons } from '@expo/vector-icons';
import { diseases, getDisease } from './src/data';
import { analyzeLeaf } from './src/services/inference';
import { deleteDiagnosis, initializeDatabase, listDiagnoses, markSynced, saveDiagnosis } from './src/services/database';
import { syncDiagnoses } from './src/services/sync';
import { authenticate, changePassword, deleteAccount, logoutSession, restoreSession, updateProfile } from './src/services/auth';
import { loadDiseaseCatalog } from './src/services/diseases';
import { Diagnosis, Disease, Session } from './src/types';

type Screen = 'home' | 'scan' | 'history' | 'guide' | 'profile';
const SAMPLE_IMAGE = require('./assets/black-sigatoka-sample.png');
const COLORS = { ink: '#17211e', muted: '#6b7571', green: '#176348', dark: '#153f34', lime: '#b6cb56', bg: '#f2f5f2', line: '#dce2de', white: '#ffffff', amber: '#b97816', red: '#b84d45' };
const createSyncUuid = () => 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (character) => { const random = Math.floor(Math.random() * 16); return (character === 'x' ? random : (random & 0x3) | 0x8).toString(16); });

function IconButton({ icon, label, onPress }: { icon: keyof typeof Ionicons.glyphMap; label: string; onPress: () => void }) {
  return <Pressable accessibilityRole="button" accessibilityLabel={label} style={({ pressed }) => [styles.iconButton, pressed && styles.pressed]} onPress={onPress}><Ionicons name={icon} size={21} color={COLORS.dark} /></Pressable>;
}

function Header({ online, pending }: { online: boolean; pending: number }) {
  return <View style={styles.header}><View style={styles.brandMark}><Ionicons name="leaf" size={20} color={COLORS.dark} /></View><View style={styles.brandCopy}><Text style={styles.brand}>BananaCare</Text><Text style={styles.brandSmall}>FIELD INTELLIGENCE</Text></View><View style={[styles.networkPill, !online && styles.networkOffline]}><Ionicons name={online ? 'cloud-done-outline' : 'cloud-offline-outline'} size={15} color={online ? COLORS.green : COLORS.amber} /><Text style={[styles.networkText, !online && { color: COLORS.amber }]}>{online ? (pending ? `${pending} pending` : 'Synced') : 'Offline'}</Text></View></View>;
}

function SectionTitle({ eyebrow, title, action }: { eyebrow: string; title: string; action?: React.ReactNode }) {
  return <View style={styles.sectionHeading}><View><Text style={styles.eyebrow}>{eyebrow}</Text><Text style={styles.sectionTitle}>{title}</Text></View>{action}</View>;
}

function DiagnosisCard({ item, onOpen }: { item: Diagnosis; onOpen: () => void }) {
  const disease = getDisease(item.diseaseId);
  return <Pressable style={({ pressed }) => [styles.diagnosisCard, pressed && styles.pressed]} onPress={onOpen}>
    <View style={[styles.diagnosisThumb, { backgroundColor: disease.status === 'healthy' ? '#e4f0e9' : '#faefd8' }]}>{item.imageUri ? <Image source={{ uri: item.imageUri }} style={styles.fillImage} /> : <Ionicons name="leaf-outline" size={22} color={COLORS.green} />}</View>
    <View style={styles.flex}><Text style={styles.cardTitle}>{disease.name}</Text><Text style={styles.cardMeta}>{new Date(item.diagnosedAt).toLocaleDateString()} · {item.modelVersion}</Text></View>
    <View style={styles.scoreRight}><Text style={styles.score}>{item.confidence.toFixed(1)}%</Text><View style={styles.syncLabel}><Ionicons name={item.synced ? 'cloud-done-outline' : 'cloud-offline-outline'} size={12} color={COLORS.muted} /><Text style={styles.tiny}>{item.synced ? 'Synced' : 'Local'}</Text></View></View>
    <Ionicons name="chevron-forward" size={17} color="#9ca7a2" />
  </Pressable>;
}

function HomeScreen({ records, online, setScreen, openRecord, name }: { records: Diagnosis[]; online: boolean; setScreen: (screen: Screen) => void; openRecord: (record: Diagnosis) => void; name: string }) {
  return <ScrollView contentContainerStyle={styles.page} showsVerticalScrollIndicator={false}>
    <View style={styles.greeting}><View><Text style={styles.eyebrow}>FIELD OVERVIEW</Text><Text style={styles.h1}>Hello, {name}.</Text><Text style={styles.subtitle}>Ready for your next field diagnosis.</Text></View><IconButton icon="notifications-outline" label="Notifications" onPress={() => Alert.alert('Notifications', 'No new research alerts.')} /></View>
    <View style={styles.hero}><View style={styles.heroBadge}><Ionicons name="sparkles" size={14} color={COLORS.lime} /><Text style={styles.heroBadgeText}>ON-DEVICE DIAGNOSIS</Text></View><Text style={styles.heroTitle}>Check a banana leaf wherever you are.</Text><Text style={styles.heroText}>Capture one clear leaf. Results save locally and sync when your connection returns.</Text><Pressable style={styles.heroButton} onPress={() => setScreen('scan')}><Ionicons name="scan" size={21} color={COLORS.dark} /><Text style={styles.heroButtonText}>Start leaf scan</Text></Pressable><View style={styles.heroStatus}><Ionicons name={online ? 'shield-checkmark-outline' : 'cloud-offline-outline'} size={16} color="#dce8a8" /><Text style={styles.heroStatusText}>{online ? 'Model ready · Internet available' : 'Model ready · Offline mode'}</Text></View></View>
    <View style={styles.stats}><View style={styles.stat}><Text style={styles.statValue}>{records.length}</Text><Text style={styles.statLabel}>Local scans</Text></View><View style={styles.statDivider} /><View style={styles.stat}><Text style={styles.statValue}>{records.filter((r) => !r.synced).length}</Text><Text style={styles.statLabel}>Waiting to sync</Text></View><View style={styles.statDivider} /><View style={styles.stat}><Text style={styles.statValue}>84ms</Text><Text style={styles.statLabel}>Avg. latency</Text></View></View>
    <SectionTitle eyebrow="RECENT ACTIVITY" title="Latest diagnoses" action={<Pressable onPress={() => setScreen('history')}><Text style={styles.textLink}>View all</Text></Pressable>} />
    <View style={styles.listCard}>{records.slice(0, 4).map((record) => <DiagnosisCard key={record.id} item={record} onOpen={() => openRecord(record)} />)}{!records.length && <View style={styles.empty}><Ionicons name="leaf-outline" size={32} color="#90a099" /><Text style={styles.emptyTitle}>No diagnoses yet</Text><Text style={styles.emptyText}>Your saved scans will appear here.</Text></View>}</View>
    <View style={styles.fieldNote}><Ionicons name="information-circle-outline" size={20} color={COLORS.green} /><Text style={styles.fieldNoteText}>Use AI results for field screening. Confirm high-impact findings with local crop authorities.</Text></View>
  </ScrollView>;
}

function ScanScreen({ online, onSaved, goHome, ownerId }: { online: boolean; onSaved: (record: Diagnosis) => Promise<void>; goHome: () => void; ownerId: number }) {
  const [imageUri, setImageUri] = useState<string | null>(null);
  const [isSample, setIsSample] = useState(false);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<Awaited<ReturnType<typeof analyzeLeaf>> | null>(null);

  const choose = async (camera: boolean) => {
    if (camera) {
      const permission = await ImagePicker.requestCameraPermissionsAsync();
      if (!permission.granted) return Alert.alert('Camera permission required', 'Enable camera access to photograph a banana leaf.');
    }
    const picker = camera ? ImagePicker.launchCameraAsync : ImagePicker.launchImageLibraryAsync;
    const response = await picker({ mediaTypes: ['images'], quality: 0.85, allowsEditing: false, cameraType: ImagePicker.CameraType.back });
    if (!response.canceled) { setImageUri(response.assets[0].uri); setIsSample(false); setResult(null); }
  };
  const useSample = () => { setImageUri(Image.resolveAssetSource(SAMPLE_IMAGE).uri); setIsSample(true); setResult(null); };
  const analyze = async () => { if (!imageUri) return; setLoading(true); try { setResult(await analyzeLeaf(imageUri)); } finally { setLoading(false); } };
  const save = async () => { if (!result) return; const diagnosis: Diagnosis = { id: createSyncUuid(), ownerId, diseaseId: result.diseaseId, confidence: result.confidence, latency: result.latency, imageUri: isSample ? null : imageUri, modelVersion: result.modelVersion, diagnosedAt: new Date().toISOString(), synced: false }; await onSaved(diagnosis); Alert.alert('Saved locally', online ? 'The result is queued for mobile API sync.' : 'It will sync when a connection is available.', [{ text: 'Done', onPress: goHome }]); };
  if (result && imageUri) return <ResultView imageUri={imageUri} result={result} onSave={save} onReset={() => { setResult(null); setImageUri(null); }} />;
  return <ScrollView contentContainerStyle={styles.page} showsVerticalScrollIndicator={false}><View style={styles.screenTop}><View><Text style={styles.eyebrow}>NEW DIAGNOSIS</Text><Text style={styles.h1}>Scan banana leaf</Text><Text style={styles.subtitle}>Keep the full leaf visible and in focus.</Text></View><View style={styles.modelPill}><View style={styles.liveDot} /><Text style={styles.modelText}>INT8 v1.4</Text></View></View>
    <View style={styles.captureFrame}>{imageUri ? <Image source={{ uri: imageUri }} style={styles.captureImage} /> : <><View style={styles.cornerTL} /><View style={styles.cornerTR} /><View style={styles.cornerBL} /><View style={styles.cornerBR} /><View style={styles.leafCircle}><Ionicons name="leaf-outline" size={46} color={COLORS.green} /></View><Text style={styles.captureTitle}>Position one leaf in frame</Text><Text style={styles.captureHint}>Avoid shadows, blur, and cluttered backgrounds.</Text></>}{loading && <View style={styles.loadingCover}><ActivityIndicator color={COLORS.lime} size="large" /><Text style={styles.loadingTitle}>Analyzing leaf tissue...</Text><Text style={styles.loadingText}>Running the local inference adapter</Text></View>}</View>
    {!imageUri ? <><Pressable style={styles.primary} onPress={() => choose(true)}><Ionicons name="camera" size={20} color={COLORS.white} /><Text style={styles.primaryText}>Open camera</Text></Pressable><View style={styles.secondaryRow}><Pressable style={styles.secondary} onPress={() => choose(false)}><Ionicons name="images-outline" size={19} color={COLORS.dark} /><Text style={styles.secondaryText}>Photo library</Text></Pressable><Pressable style={styles.secondary} onPress={useSample}><Ionicons name="flask-outline" size={19} color={COLORS.dark} /><Text style={styles.secondaryText}>Use sample</Text></Pressable></View></> : <><Pressable style={styles.primary} disabled={loading} onPress={analyze}><Ionicons name="scan" size={20} color={COLORS.white} /><Text style={styles.primaryText}>Analyze leaf</Text></Pressable><Pressable style={styles.changeImage} onPress={() => { setImageUri(null); setResult(null); }}><Text style={styles.textLink}>Choose another image</Text></Pressable></>}
    <View style={styles.checkRow}>{[['leaf-outline','One leaf'],['sunny-outline','Natural light'],['aperture-outline','Sharp focus']].map(([icon,label]) => <View style={styles.checkItem} key={label}><Ionicons name={icon as keyof typeof Ionicons.glyphMap} size={15} color={COLORS.green} /><Text style={styles.checkText}>{label}</Text></View>)}</View>
    <View style={styles.demoNotice}><Ionicons name="information-circle-outline" size={18} color={COLORS.amber} /><Text style={styles.demoText}>Inference is simulated until the final thesis TFLite model is added.</Text></View>
  </ScrollView>;
}

function ResultView({ imageUri, result, onSave, onReset }: { imageUri: string; result: Awaited<ReturnType<typeof analyzeLeaf>>; onSave: () => void; onReset: () => void }) {
  const disease = getDisease(result.diseaseId);
  return <ScrollView contentContainerStyle={styles.page} showsVerticalScrollIndicator={false}><Pressable style={styles.back} onPress={onReset}><Ionicons name="arrow-back" size={18} color={COLORS.green} /><Text style={styles.textLink}>New scan</Text></Pressable><Text style={styles.eyebrow}>DIAGNOSIS COMPLETE</Text><Text style={styles.h1}>Analysis result</Text>
    <View style={styles.resultImageWrap}><Image source={{ uri: imageUri }} style={styles.resultImage} /><View style={styles.attentionOne} /><View style={styles.attentionTwo} /><View style={styles.demoOverlay}><Text style={styles.demoOverlayText}>ATTENTION PREVIEW</Text></View></View>
    <View style={styles.resultCard}><View style={styles.resultHeader}><View style={styles.alertIcon}><Ionicons name="warning-outline" size={22} color={COLORS.red} /></View><View style={styles.flex}><Text style={styles.detected}>DISEASE DETECTED</Text><Text style={styles.resultDisease}>{disease.name}</Text><Text style={styles.scientific}>{disease.scientific}</Text></View></View><View style={styles.confidenceRow}><Text style={styles.confidenceLabel}>Model confidence</Text><Text style={styles.confidence}>{result.confidence.toFixed(1)}%</Text></View><View style={styles.progress}><View style={[styles.progressFill, { width: `${result.confidence}%` }]} /></View><View style={styles.resultMeta}><Text style={styles.metaText}>Inference {result.latency} ms</Text><Text style={styles.metaText}>{result.modelVersion}</Text></View></View>
    <View style={styles.guidance}><Text style={styles.eyebrow}>WHAT TO LOOK FOR</Text>{disease.symptoms.map((symptom) => <View style={styles.symptom} key={symptom}><View style={styles.symptomDot} /><Text style={styles.symptomText}>{symptom}</Text></View>)}</View>
    <View style={styles.actionBox}><Ionicons name="shield-checkmark-outline" size={22} color={COLORS.green} /><View style={styles.flex}><Text style={styles.actionTitle}>Recommended action</Text><Text style={styles.actionText}>{disease.management}</Text></View></View>
    <Pressable style={styles.primary} onPress={onSave}><Ionicons name="save-outline" size={20} color={COLORS.white} /><Text style={styles.primaryText}>Save diagnosis</Text></Pressable>
  </ScrollView>;
}

function HistoryScreen({ records, openRecord }: { records: Diagnosis[]; openRecord: (record: Diagnosis) => void }) {
  return <ScrollView contentContainerStyle={styles.page} showsVerticalScrollIndicator={false}><Text style={styles.eyebrow}>OFFLINE RECORDS</Text><Text style={styles.h1}>Diagnosis history</Text><Text style={styles.subtitle}>{records.length} scans saved on this device</Text><View style={[styles.listCard, { marginTop: 22 }]}>{records.map((record) => <DiagnosisCard key={record.id} item={record} onOpen={() => openRecord(record)} />)}{!records.length && <View style={styles.empty}><Ionicons name="time-outline" size={34} color="#90a099" /><Text style={styles.emptyTitle}>History is empty</Text><Text style={styles.emptyText}>Complete a leaf scan to create your first record.</Text></View>}</View></ScrollView>;
}

function GuideScreen() {
  const [catalog, setCatalog] = useState<Disease[]>([]); const [selected, setSelected] = useState<Disease | null>(null); const [loaded, setLoaded] = useState(false);
  useEffect(() => { loadDiseaseCatalog().then((items) => { setCatalog(items); setSelected(items[0] ?? null); }).finally(() => setLoaded(true)); }, []);
  return <ScrollView contentContainerStyle={styles.page} showsVerticalScrollIndicator={false}><Text style={styles.eyebrow}>FIELD REFERENCE</Text><Text style={styles.h1}>Disease guide</Text><Text style={styles.subtitle}>Disease information managed by the central API and cached for offline reference.</Text>{!loaded && <ActivityIndicator color={COLORS.green} style={{ marginTop: 30 }} />}{loaded && !selected && <View style={styles.empty}><Ionicons name="book-outline" size={34} color="#90a099" /><Text style={styles.emptyTitle}>No disease records</Text><Text style={styles.emptyText}>An administrator can add records after the final label map is available.</Text></View>}{selected && <><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.guideTabs}>{catalog.map((disease) => <Pressable key={disease.id} onPress={() => setSelected(disease)} style={[styles.guideTab, selected.id === disease.id && styles.guideTabActive]}><Ionicons name="leaf-outline" size={17} color={selected.id === disease.id ? COLORS.white : COLORS.green} /><Text style={[styles.guideTabText, selected.id === disease.id && { color: COLORS.white }]}>{disease.name}</Text></Pressable>)}</ScrollView><View style={styles.guideCard}><View style={[styles.guideIcon, selected.status === 'critical' && { backgroundColor: '#f8e5e3' }]}><Ionicons name="leaf" size={28} color={selected.status === 'critical' ? COLORS.red : COLORS.green} /></View><Text style={styles.guideTitle}>{selected.name}</Text><Text style={styles.scientific}>{selected.scientific}</Text><Text style={styles.guideSummary}>{selected.summary}</Text><Text style={styles.eyebrow}>COMMON SYMPTOMS</Text>{selected.symptoms.map((symptom) => <View style={styles.symptom} key={symptom}><Ionicons name="checkmark-circle" size={17} color={COLORS.green} /><Text style={styles.symptomText}>{symptom}</Text></View>)}<View style={styles.actionBox}><Ionicons name="shield-checkmark-outline" size={22} color={COLORS.green} /><View style={styles.flex}><Text style={styles.actionTitle}>Management guidance</Text><Text style={styles.actionText}>{selected.management}</Text></View></View></View></>}</ScrollView>;
}

function RecordModal({ record, onClose, onDelete }: { record: Diagnosis | null; onClose: () => void; onDelete: (id: string) => void }) {
  if (!record) return null; const disease = getDisease(record.diseaseId);
  return <Modal visible animationType="slide" presentationStyle="pageSheet" onRequestClose={onClose}><SafeAreaView style={styles.modalRoot}><View style={styles.modalHeader}><View><Text style={styles.eyebrow}>DIAGNOSIS RECORD</Text><Text style={styles.modalId}>{record.id}</Text></View><IconButton icon="close" label="Close" onPress={onClose} /></View><ScrollView contentContainerStyle={styles.modalPage}>{record.imageUri ? <Image source={{ uri: record.imageUri }} style={styles.modalImage} /> : <View style={[styles.modalImage, styles.modalPlaceholder]}><Ionicons name="leaf-outline" size={46} color={COLORS.green} /></View>}<Text style={styles.resultDisease}>{disease.name}</Text><Text style={styles.scientific}>{disease.scientific}</Text><View style={styles.modalScore}><Text style={styles.confidenceLabel}>Confidence</Text><Text style={styles.confidence}>{record.confidence.toFixed(1)}%</Text></View>{[['Date', new Date(record.diagnosedAt).toLocaleString()],['Inference', `${record.latency} ms`],['Model',record.modelVersion],['Cloud',record.synced ? 'Synced' : 'Saved locally']].map(([label,value]) => <View style={styles.detailRow} key={label}><Text style={styles.detailLabel}>{label}</Text><Text style={styles.detailValue}>{value}</Text></View>)}<View style={styles.actionBox}><Ionicons name="shield-checkmark-outline" size={22} color={COLORS.green} /><Text style={[styles.actionText, styles.flex]}>{disease.management}</Text></View><Pressable style={styles.deleteButton} onPress={() => Alert.alert('Delete diagnosis?', 'This removes the local record from this device.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: () => onDelete(record.id) }])}><Ionicons name="trash-outline" size={18} color={COLORS.red} /><Text style={styles.deleteText}>Delete local record</Text></Pressable></ScrollView></SafeAreaView></Modal>;
}

function AuthScreen({ onAuthenticated }: { onAuthenticated: (session: Session) => void }) {
  const [signup, setSignup] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const [form, setForm] = useState({ name: '', email: '', password: '', password_confirmation: '' });
  const submit = async () => { setBusy(true); setError(''); try { onAuthenticated(await authenticate(signup ? 'register' : 'login', form)); } catch (exception) { setError(exception instanceof Error ? exception.message : 'Authentication failed.'); } finally { setBusy(false); } };
  return <SafeAreaView style={styles.authRoot}><StatusBar style="light" /><View style={styles.authMark}><Ionicons name="leaf" size={34} color={COLORS.dark} /></View><Text style={styles.authBrand}>BananaCare</Text><Text style={styles.authTag}>FIELD INTELLIGENCE</Text><View style={styles.authCard}><Text style={styles.eyebrow}>{signup ? 'CREATE ACCOUNT' : 'WELCOME BACK'}</Text><Text style={styles.authTitle}>{signup ? 'Start your field workspace' : 'Sign in to continue'}</Text>{signup && <TextInput style={styles.input} placeholder="Full name" value={form.name} onChangeText={(name) => setForm({ ...form, name })} autoCapitalize="words" />}<TextInput style={styles.input} placeholder="Email" value={form.email} onChangeText={(email) => setForm({ ...form, email })} keyboardType="email-address" autoCapitalize="none" autoComplete="email" /><TextInput style={styles.input} placeholder="Password" value={form.password} onChangeText={(password) => setForm({ ...form, password })} secureTextEntry autoComplete={signup ? 'new-password' : 'current-password'} />{signup && <TextInput style={styles.input} placeholder="Confirm password" value={form.password_confirmation} onChangeText={(password_confirmation) => setForm({ ...form, password_confirmation })} secureTextEntry />}{Boolean(error) && <Text style={styles.formError}>{error}</Text>}<Pressable style={styles.primary} disabled={busy} onPress={submit}>{busy ? <ActivityIndicator color={COLORS.white} /> : <Text style={styles.primaryText}>{signup ? 'Create account' : 'Sign in'}</Text>}</Pressable><Pressable style={styles.authSwitch} onPress={() => { setSignup(!signup); setError(''); }}><Text style={styles.authSwitchText}>{signup ? 'Already registered? Sign in' : 'Need an account? Sign up'}</Text></Pressable></View></SafeAreaView>;
}

function ProfileScreen({ session, onSession, onLogout }: { session: Session; onSession: (session: Session) => void; onLogout: () => void }) {
  const [profile, setProfile] = useState({ name: session.user.name, email: session.user.email }); const [showPassword, setShowPassword] = useState(false);
  const [passwords, setPasswords] = useState({ current_password: '', password: '', password_confirmation: '' }); const [busy, setBusy] = useState(false);
  const saveProfile = async () => { setBusy(true); try { onSession(await updateProfile(session, profile)); Alert.alert('Profile updated'); } catch (exception) { Alert.alert('Unable to update', exception instanceof Error ? exception.message : 'Try again.'); } finally { setBusy(false); } };
  const savePassword = async () => { setBusy(true); try { await changePassword(session, passwords); setPasswords({ current_password: '', password: '', password_confirmation: '' }); setShowPassword(false); Alert.alert('Password updated'); } catch (exception) { Alert.alert('Unable to update', exception instanceof Error ? exception.message : 'Try again.'); } finally { setBusy(false); } };
  return <ScrollView contentContainerStyle={styles.page}><Text style={styles.eyebrow}>ACCOUNT</Text><Text style={styles.h1}>Profile</Text><View style={styles.profileAvatar}><Text style={styles.profileInitial}>{session.user.name.slice(0, 1).toUpperCase()}</Text></View><View style={styles.profileCard}><Text style={styles.inputLabel}>Name</Text><TextInput style={styles.input} value={profile.name} onChangeText={(name) => setProfile({ ...profile, name })} /><Text style={styles.inputLabel}>Email</Text><TextInput style={styles.input} value={profile.email} onChangeText={(email) => setProfile({ ...profile, email })} keyboardType="email-address" autoCapitalize="none" /><Pressable style={styles.primary} disabled={busy} onPress={saveProfile}><Text style={styles.primaryText}>Save profile</Text></Pressable><Pressable style={styles.profileAction} onPress={() => setShowPassword(!showPassword)}><Ionicons name="key-outline" size={18} color={COLORS.green} /><Text style={styles.profileActionText}>Change password</Text></Pressable>{showPassword && <View><TextInput style={styles.input} placeholder="Current password" secureTextEntry value={passwords.current_password} onChangeText={(current_password) => setPasswords({ ...passwords, current_password })} /><TextInput style={styles.input} placeholder="New password" secureTextEntry value={passwords.password} onChangeText={(password) => setPasswords({ ...passwords, password })} /><TextInput style={styles.input} placeholder="Confirm new password" secureTextEntry value={passwords.password_confirmation} onChangeText={(password_confirmation) => setPasswords({ ...passwords, password_confirmation })} /><Pressable style={styles.secondary} disabled={busy} onPress={savePassword}><Text style={styles.secondaryText}>Update password</Text></Pressable></View>}<Pressable style={styles.profileAction} onPress={onLogout}><Ionicons name="log-out-outline" size={18} color={COLORS.red} /><Text style={[styles.profileActionText, { color: COLORS.red }]}>Log out</Text></Pressable><Pressable style={styles.deleteButton} onPress={() => Alert.alert('Delete account?', 'This deletes the account and its server diagnosis records.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: async () => { try { await deleteAccount(session); onLogout(); } catch (exception) { Alert.alert('Unable to delete', exception instanceof Error ? exception.message : 'Connect to the Internet and try again.'); } } }])}><Text style={styles.deleteText}>Delete account</Text></Pressable></View></ScrollView>;
}

const TABS: { id: Screen; label: string; icon: keyof typeof Ionicons.glyphMap }[] = [{ id: 'home', label: 'Home', icon: 'home-outline' }, { id: 'scan', label: 'Scan', icon: 'scan-outline' }, { id: 'history', label: 'History', icon: 'time-outline' }, { id: 'guide', label: 'Guide', icon: 'book-outline' }, { id: 'profile', label: 'Profile', icon: 'person-outline' }];

export default function App() {
  const [screen, setScreen] = useState<Screen>('home'); const [records, setRecords] = useState<Diagnosis[]>([]); const [online, setOnline] = useState(false); const [selected, setSelected] = useState<Diagnosis | null>(null); const [ready, setReady] = useState(false); const [session, setSession] = useState<Session | null>(null);
  const refresh = useCallback(async () => setRecords(session ? await listDiagnoses(session.user.id) : []), [session]);
  useEffect(() => { Promise.all([initializeDatabase(), restoreSession()]).then(([, restored]) => setSession(restored)).finally(() => setReady(true)); const unsubscribe = NetInfo.addEventListener((state) => setOnline(Boolean(state.isConnected && state.isInternetReachable !== false))); return unsubscribe; }, []);
  useEffect(() => { refresh(); }, [refresh]);
  useEffect(() => { if (!session || !online || !records.some((record) => !record.synced)) return; const pending = records.filter((record) => !record.synced); syncDiagnoses(pending).then(async (ids) => { if (!ids.length) return; await markSynced(ids); await refresh(); }).catch(() => undefined); }, [session, online, records, refresh]);
  const pending = useMemo(() => records.filter((record) => !record.synced).length, [records]);
  const addRecord = async (record: Diagnosis) => { await saveDiagnosis(record); await refresh(); };
  const removeRecord = async (id: string) => { await deleteDiagnosis(id); setSelected(null); await refresh(); };
  if (!ready) return <View style={styles.boot}><View style={styles.bootMark}><Ionicons name="leaf" size={38} color={COLORS.dark} /></View><ActivityIndicator color={COLORS.lime} /><Text style={styles.bootText}>Preparing offline field data...</Text></View>;
  if (!session) return <AuthScreen onAuthenticated={setSession} />;
  const signOut = async () => { await logoutSession(session); setSession(null); setRecords([]); setScreen('home'); };
  return <SafeAreaView style={styles.safe}><StatusBar style="dark" /><NativeStatusBar backgroundColor={COLORS.white} barStyle="dark-content" /><Header online={online} pending={pending} /><View style={styles.content}>{screen === 'home' && <HomeScreen records={records} online={online} setScreen={setScreen} openRecord={setSelected} name={session.user.name.split(' ')[0]} />}{screen === 'scan' && <ScanScreen online={online} onSaved={addRecord} goHome={() => setScreen('home')} ownerId={session.user.id} />}{screen === 'history' && <HistoryScreen records={records} openRecord={setSelected} />}{screen === 'guide' && <GuideScreen />}{screen === 'profile' && <ProfileScreen session={session} onSession={setSession} onLogout={signOut} />}</View><View style={styles.tabs}>{TABS.map((tab) => <Pressable key={tab.id} style={styles.tab} onPress={() => setScreen(tab.id)}><View style={[styles.tabIcon, screen === tab.id && styles.tabIconActive]}><Ionicons name={screen === tab.id ? tab.icon.replace('-outline', '') as keyof typeof Ionicons.glyphMap : tab.icon} size={21} color={screen === tab.id ? COLORS.white : '#7d8984'} /></View><Text style={[styles.tabLabel, screen === tab.id && styles.tabLabelActive]}>{tab.label}</Text></Pressable>)}</View><RecordModal record={selected} onClose={() => setSelected(null)} onDelete={removeRecord} /></SafeAreaView>;
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: COLORS.white, paddingTop: Platform.OS === 'android' ? NativeStatusBar.currentHeight : 0 }, content: { flex: 1, backgroundColor: COLORS.bg }, page: { padding: 20, paddingBottom: 36 }, flex: { flex: 1 }, pressed: { opacity: 0.74 },
  header: { height: 62, paddingHorizontal: 18, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderColor: COLORS.line, backgroundColor: COLORS.white }, brandMark: { width: 36, height: 36, borderRadius: 7, alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS.lime }, brandCopy: { flex: 1, marginLeft: 10 }, brand: { color: COLORS.dark, fontSize: 16, fontWeight: '800' }, brandSmall: { marginTop: 1, color: COLORS.muted, fontSize: 8, fontWeight: '700', letterSpacing: 1 }, networkPill: { height: 29, paddingHorizontal: 9, borderRadius: 15, flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: '#e5f1eb' }, networkOffline: { backgroundColor: '#faefd8' }, networkText: { color: COLORS.green, fontSize: 10, fontWeight: '700' },
  greeting: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }, eyebrow: { color: '#74817c', fontSize: 9, fontWeight: '800', letterSpacing: 1.2, marginBottom: 7 }, h1: { color: COLORS.ink, fontSize: 28, lineHeight: 34, fontWeight: '800' }, subtitle: { color: COLORS.muted, fontSize: 13, lineHeight: 19, marginTop: 3 }, iconButton: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center', backgroundColor: '#eef2ef' },
  hero: { marginTop: 22, padding: 22, borderRadius: 8, backgroundColor: COLORS.dark }, heroBadge: { flexDirection: 'row', alignItems: 'center', gap: 6 }, heroBadgeText: { color: COLORS.lime, fontSize: 9, fontWeight: '800', letterSpacing: 1 }, heroTitle: { color: COLORS.white, fontSize: 26, lineHeight: 32, fontWeight: '800', marginTop: 15 }, heroText: { color: '#bfd2ca', fontSize: 13, lineHeight: 20, marginTop: 9 }, heroButton: { height: 50, marginTop: 20, borderRadius: 6, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 9, backgroundColor: COLORS.lime }, heroButtonText: { color: COLORS.dark, fontSize: 15, fontWeight: '800' }, heroStatus: { marginTop: 15, flexDirection: 'row', alignItems: 'center', gap: 7 }, heroStatusText: { color: '#c8d8d1', fontSize: 10, fontWeight: '600' },
  stats: { minHeight: 78, marginTop: 14, borderRadius: 7, flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.line }, stat: { flex: 1, alignItems: 'center' }, statValue: { color: COLORS.ink, fontSize: 17, fontWeight: '800' }, statLabel: { color: COLORS.muted, fontSize: 9, marginTop: 3, textAlign: 'center' }, statDivider: { width: 1, height: 34, backgroundColor: COLORS.line },
  sectionHeading: { marginTop: 27, marginBottom: 12, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end' }, sectionTitle: { color: COLORS.ink, fontSize: 18, fontWeight: '800' }, textLink: { color: COLORS.green, fontSize: 12, fontWeight: '800' }, listCard: { overflow: 'hidden', borderRadius: 7, backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.line }, diagnosisCard: { minHeight: 72, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 10, borderBottomWidth: StyleSheet.hairlineWidth, borderColor: COLORS.line }, diagnosisThumb: { width: 45, height: 45, overflow: 'hidden', borderRadius: 6, alignItems: 'center', justifyContent: 'center' }, fillImage: { width: '100%', height: '100%' }, cardTitle: { color: COLORS.ink, fontSize: 12, fontWeight: '800' }, cardMeta: { color: COLORS.muted, fontSize: 9, marginTop: 3 }, scoreRight: { alignItems: 'flex-end' }, score: { color: COLORS.green, fontSize: 12, fontWeight: '800' }, syncLabel: { marginTop: 4, flexDirection: 'row', gap: 3, alignItems: 'center' }, tiny: { color: COLORS.muted, fontSize: 8 }, empty: { minHeight: 180, alignItems: 'center', justifyContent: 'center' }, emptyTitle: { color: COLORS.ink, fontSize: 14, fontWeight: '800', marginTop: 8 }, emptyText: { color: COLORS.muted, fontSize: 11, marginTop: 3 }, fieldNote: { marginTop: 15, padding: 13, borderRadius: 6, flexDirection: 'row', gap: 9, backgroundColor: '#e8f1ec' }, fieldNoteText: { flex: 1, color: '#51645d', fontSize: 10, lineHeight: 15 },
  screenTop: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between' }, modelPill: { height: 29, paddingHorizontal: 9, flexDirection: 'row', alignItems: 'center', gap: 6, borderRadius: 5, borderWidth: 1, borderColor: COLORS.line, backgroundColor: COLORS.white }, liveDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: '#58a16b' }, modelText: { color: COLORS.muted, fontSize: 9, fontWeight: '700' }, captureFrame: { height: 390, marginTop: 22, overflow: 'hidden', borderRadius: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: '#e4ebe7' }, captureImage: { width: '100%', height: '100%', resizeMode: 'cover' }, leafCircle: { width: 84, height: 84, borderRadius: 42, alignItems: 'center', justifyContent: 'center', backgroundColor: '#f8fbf9' }, captureTitle: { color: COLORS.ink, fontSize: 15, fontWeight: '800', marginTop: 17 }, captureHint: { maxWidth: 240, color: COLORS.muted, fontSize: 11, lineHeight: 17, marginTop: 5, textAlign: 'center' }, cornerTL: { position: 'absolute', top: 28, left: 28, width: 42, height: 42, borderTopWidth: 2, borderLeftWidth: 2, borderColor: COLORS.green }, cornerTR: { position: 'absolute', top: 28, right: 28, width: 42, height: 42, borderTopWidth: 2, borderRightWidth: 2, borderColor: COLORS.green }, cornerBL: { position: 'absolute', bottom: 28, left: 28, width: 42, height: 42, borderBottomWidth: 2, borderLeftWidth: 2, borderColor: COLORS.green }, cornerBR: { position: 'absolute', bottom: 28, right: 28, width: 42, height: 42, borderBottomWidth: 2, borderRightWidth: 2, borderColor: COLORS.green }, loadingCover: { ...StyleSheet.absoluteFillObject, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(15,44,35,.84)' }, loadingTitle: { color: COLORS.white, fontSize: 15, fontWeight: '800', marginTop: 13 }, loadingText: { color: '#bdd0c8', fontSize: 10, marginTop: 4 },
  primary: { height: 50, marginTop: 14, borderRadius: 6, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 9, backgroundColor: COLORS.green }, primaryText: { color: COLORS.white, fontSize: 14, fontWeight: '800' }, secondaryRow: { flexDirection: 'row', gap: 10, marginTop: 10 }, secondary: { flex: 1, height: 46, borderRadius: 6, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, backgroundColor: COLORS.white, borderWidth: 1, borderColor: '#cdd7d2' }, secondaryText: { color: COLORS.dark, fontSize: 11, fontWeight: '800' }, changeImage: { alignSelf: 'center', padding: 11 }, checkRow: { marginTop: 17, flexDirection: 'row', justifyContent: 'space-around' }, checkItem: { flexDirection: 'row', alignItems: 'center', gap: 4 }, checkText: { color: COLORS.muted, fontSize: 9 }, demoNotice: { marginTop: 19, padding: 12, borderRadius: 5, flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: '#faefd8' }, demoText: { flex: 1, color: '#76531d', fontSize: 10, lineHeight: 15 },
  back: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 5, marginBottom: 13 }, resultImageWrap: { height: 310, marginTop: 20, overflow: 'hidden', borderRadius: 8, backgroundColor: COLORS.dark }, resultImage: { width: '100%', height: '100%', resizeMode: 'cover' }, attentionOne: { position: 'absolute', width: 125, height: 125, borderRadius: 70, right: 55, bottom: 55, backgroundColor: 'rgba(242,78,34,.33)', borderWidth: 25, borderColor: 'rgba(246,181,39,.24)' }, attentionTwo: { position: 'absolute', width: 80, height: 80, borderRadius: 45, left: 75, bottom: 50, backgroundColor: 'rgba(231,71,34,.22)' }, demoOverlay: { position: 'absolute', left: 10, bottom: 10, paddingHorizontal: 8, paddingVertical: 5, borderRadius: 3, backgroundColor: 'rgba(12,23,19,.8)' }, demoOverlayText: { color: COLORS.white, fontSize: 8, fontWeight: '800', letterSpacing: .8 }, resultCard: { marginTop: 13, padding: 17, borderRadius: 7, backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.line }, resultHeader: { flexDirection: 'row', gap: 11 }, alertIcon: { width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center', backgroundColor: '#f8e5e3' }, detected: { color: COLORS.red, fontSize: 8, fontWeight: '800', letterSpacing: 1 }, resultDisease: { color: COLORS.ink, fontSize: 23, fontWeight: '800', marginTop: 4 }, scientific: { color: COLORS.muted, fontSize: 11, fontStyle: 'italic', marginTop: 2 }, confidenceRow: { marginTop: 20, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, confidenceLabel: { color: COLORS.muted, fontSize: 11 }, confidence: { color: COLORS.green, fontSize: 24, fontWeight: '800' }, progress: { height: 7, marginTop: 8, overflow: 'hidden', borderRadius: 5, backgroundColor: '#dfe6e2' }, progressFill: { height: '100%', borderRadius: 5, backgroundColor: COLORS.green }, resultMeta: { marginTop: 10, flexDirection: 'row', justifyContent: 'space-between' }, metaText: { color: COLORS.muted, fontSize: 9 }, guidance: { marginTop: 13, padding: 17, borderRadius: 7, backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.line }, symptom: { minHeight: 31, flexDirection: 'row', alignItems: 'center', gap: 8 }, symptomDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: COLORS.amber }, symptomText: { flex: 1, color: '#46534e', fontSize: 11 }, actionBox: { marginTop: 15, padding: 14, borderRadius: 6, flexDirection: 'row', alignItems: 'flex-start', gap: 10, backgroundColor: '#e7f1ec', borderLeftWidth: 3, borderLeftColor: COLORS.green }, actionTitle: { color: COLORS.dark, fontSize: 12, fontWeight: '800' }, actionText: { color: '#52655e', fontSize: 10, lineHeight: 16, marginTop: 4 },
  guideTabs: { paddingVertical: 18, gap: 8 }, guideTab: { minHeight: 37, paddingHorizontal: 12, borderRadius: 5, flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.line }, guideTabActive: { backgroundColor: COLORS.green, borderColor: COLORS.green }, guideTabText: { color: COLORS.dark, fontSize: 10, fontWeight: '700' }, guideCard: { padding: 21, borderRadius: 8, backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.line }, guideIcon: { width: 53, height: 53, borderRadius: 7, alignItems: 'center', justifyContent: 'center', backgroundColor: '#e4f0e9' }, guideTitle: { color: COLORS.ink, fontSize: 23, fontWeight: '800', marginTop: 15 }, guideSummary: { color: '#4f5d58', fontSize: 13, lineHeight: 20, marginVertical: 21 },
  tabs: { height: 69, flexDirection: 'row', backgroundColor: COLORS.white, borderTopWidth: 1, borderColor: COLORS.line }, tab: { flex: 1, alignItems: 'center', justifyContent: 'center' }, tabIcon: { width: 34, height: 29, borderRadius: 16, alignItems: 'center', justifyContent: 'center' }, tabIconActive: { backgroundColor: COLORS.green }, tabLabel: { color: '#7c8783', fontSize: 9, fontWeight: '600', marginTop: 2 }, tabLabelActive: { color: COLORS.green, fontWeight: '800' },
  modalRoot: { flex: 1, backgroundColor: COLORS.white }, modalHeader: { minHeight: 68, paddingHorizontal: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderColor: COLORS.line }, modalId: { color: COLORS.ink, fontSize: 18, fontWeight: '800' }, modalPage: { padding: 20, paddingBottom: 40 }, modalImage: { width: '100%', height: 280, borderRadius: 7, resizeMode: 'cover' }, modalPlaceholder: { alignItems: 'center', justifyContent: 'center', backgroundColor: '#e7ede9' }, modalScore: { marginTop: 22, padding: 15, borderRadius: 6, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#f3f6f4' }, detailRow: { minHeight: 45, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: StyleSheet.hairlineWidth, borderColor: COLORS.line }, detailLabel: { color: COLORS.muted, fontSize: 10 }, detailValue: { maxWidth: '67%', color: COLORS.ink, fontSize: 10, fontWeight: '700', textAlign: 'right' }, deleteButton: { height: 46, marginTop: 22, borderRadius: 6, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, borderWidth: 1, borderColor: '#e5b8b4' }, deleteText: { color: COLORS.red, fontSize: 11, fontWeight: '800' },
  boot: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 14, backgroundColor: COLORS.dark }, bootMark: { width: 70, height: 70, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS.lime }, bootText: { color: '#c3d4cd', fontSize: 11 },
  authRoot: { flex: 1, paddingHorizontal: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS.dark }, authMark: { width: 66, height: 66, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS.lime }, authBrand: { marginTop: 12, color: COLORS.white, fontSize: 23, fontWeight: '800' }, authTag: { marginTop: 3, marginBottom: 25, color: '#adc3ba', fontSize: 8, fontWeight: '800', letterSpacing: 1.5 }, authCard: { width: '100%', maxWidth: 460, padding: 22, borderRadius: 9, backgroundColor: COLORS.white }, authTitle: { marginBottom: 18, color: COLORS.ink, fontSize: 23, lineHeight: 29, fontWeight: '800' }, input: { height: 47, marginTop: 10, paddingHorizontal: 12, color: COLORS.ink, backgroundColor: '#f9fbf9', borderWidth: 1, borderColor: '#ccd6d1', borderRadius: 6, fontSize: 13 }, formError: { marginTop: 12, padding: 10, color: COLORS.red, backgroundColor: '#f8e5e3', borderRadius: 5, fontSize: 11 }, authSwitch: { padding: 15, alignItems: 'center' }, authSwitchText: { color: COLORS.green, fontSize: 11, fontWeight: '800' },
  profileAvatar: { width: 68, height: 68, marginTop: 20, borderRadius: 34, alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS.green }, profileInitial: { color: COLORS.white, fontSize: 27, fontWeight: '800' }, profileCard: { marginTop: 15, padding: 18, borderRadius: 8, backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.line }, inputLabel: { marginTop: 12, color: COLORS.muted, fontSize: 10, fontWeight: '700' }, profileAction: { minHeight: 49, marginTop: 12, flexDirection: 'row', alignItems: 'center', gap: 9, borderTopWidth: StyleSheet.hairlineWidth, borderColor: COLORS.line }, profileActionText: { color: COLORS.green, fontSize: 12, fontWeight: '800' },
});
