import { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import Ionicons from '@expo/vector-icons/Ionicons';

import { CLASS_KEYS } from '../classification/disease-data';
import { api, authenticatedImageSource, SessionUser } from '../../services/api';
import { ActionButton, Choice, ConfirmSheet, Empty, Field, formatDate, Loading, ModalSheet, Notice, palette, SectionHeader, titleCase, Toggle, uiStyles } from './ui';

type AdminSection = 'overview' | 'accounts' | 'diagnoses' | 'diseases' | 'sources';
type ManagedUser = SessionUser & { created_at?: string; diagnoses_count?: number; last_activity_at?: string };
type Diagnosis = {
  id: number; predicted_class: string; confidence: number; source?: string; diagnosed_at?: string; created_at?: string;
  image_url?: string | null; gradcam_url?: string | null; farmer_notes?: string | null; model_version?: string | null;
  inference_time_ms?: number | null; sync_status?: string | null; user?: ManagedUser; disease?: { name?: string };
};
type DiseaseRecord = {
  id: number; slug: string; model_class_key: string; name: string; alternative_names?: string[]; scientific_name?: string | null;
  causal_agent?: string | null; pathogen_type?: string | null; short_description?: string | null; description?: string | null;
  farmer_summary?: string | null; curative_status: string; evidence_level: string; verification_status?: string;
  image_only_limitations?: string | null; professional_referral?: string | null; prevention?: string | null;
  management?: string | null; sources_count?: number; last_reviewed_at?: string | null;
};
type DiseaseDetail = { disease: DiseaseRecord; evidence?: Array<{ id: number; claim_type: string; claim_text: string; evidence_strength: string }>; regulatory_recheck_required?: boolean };
type ResearchSource = {
  id: number; title: string; authors: string; year?: number | null; journal_or_institution: string; source_type: string;
  doi?: string | null; reference_url?: string | null; country_or_region?: string | null; peer_reviewed: boolean;
  philippines_specific: boolean; notes?: string | null; evidence_count?: number;
  evidence?: Array<{ id: number; claim_type: string; claim_text: string; evidence_strength: string; disease?: { name?: string } }>;
};

const nav: Array<{ id: AdminSection; label: string; icon: keyof typeof Ionicons.glyphMap }> = [
  { id: 'overview', label: 'Overview', icon: 'grid-outline' }, { id: 'accounts', label: 'Accounts', icon: 'people-outline' },
  { id: 'diagnoses', label: 'Diagnoses', icon: 'scan-outline' }, { id: 'diseases', label: 'Diseases', icon: 'book-outline' },
  { id: 'sources', label: 'Sources', icon: 'link-outline' },
];

function messageOf(error: unknown) { return error instanceof Error ? error.message : 'The request could not be completed.'; }

export function AdminWorkspace({ user, onSignOut }: { user: SessionUser; onSignOut: () => Promise<void> }) {
  const [section, setSection] = useState<AdminSection>('overview');
  const [signingOut, setSigningOut] = useState(false);
  return (
    <View style={styles.workspace}>
      <View style={styles.adminHeader}>
        <View style={uiStyles.flex}><Text style={styles.kicker}>CONNECTED ADMIN</Text><Text style={styles.adminName}>{user.name}</Text><Text style={styles.adminEmail}>{user.email}</Text></View>
        <Pressable accessibilityRole="button" accessibilityLabel="Sign out" style={styles.signOut} disabled={signingOut} onPress={async () => { setSigningOut(true); await onSignOut(); }}>
          {signingOut ? <ActivityIndicator size="small" color={palette.green} /> : <Ionicons name="log-out-outline" size={21} color={palette.green} />}
        </Pressable>
      </View>
      <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.nav}>
        {nav.map((item) => <Pressable key={item.id} accessibilityRole="tab" accessibilityState={{ selected: section === item.id }} onPress={() => setSection(item.id)} style={[styles.navItem, section === item.id && styles.navItemActive]}><Ionicons name={item.icon} size={17} color={section === item.id ? '#fff' : palette.green} /><Text style={[styles.navText, section === item.id && styles.navTextActive]}>{item.label}</Text></Pressable>)}
      </ScrollView>
      {section === 'overview' && <OverviewScreen />}
      {section === 'accounts' && <AccountsScreen />}
      {section === 'diagnoses' && <DiagnosesScreen />}
      {section === 'diseases' && <DiseasesScreen />}
      {section === 'sources' && <SourcesScreen />}
    </View>
  );
}

function OverviewScreen() {
  const [data, setData] = useState<Record<string, any> | null>(null);
  const [error, setError] = useState('');
  const load = useCallback(async () => { try { const result = await api<Record<string, any>>('/admin/dashboard'); setData(result.data); setError(''); } catch (e) { setError(messageOf(e)); } }, []);
  useEffect(() => { load(); }, [load]);
  const metrics = data ? [
    ['Farmers', data.total_farmers], ['Diagnoses', data.total_diagnoses], ['Scans today', data.diagnoses_today],
    ['Avg. confidence', `${Number(data.average_confidence || 0).toFixed(1)}%`], ['Uncertain', data.uncertain_predictions], ['Pending sync', data.pending_or_failed_syncs],
  ] : [];
  return <View style={uiStyles.stack}><SectionHeader eyebrow="ADMIN DASHBOARD" title="System overview" text="Live values from the connected database. These cards are unavailable offline; leaf classification is unaffected." action={<ActionButton variant="secondary" icon="refresh" onPress={load}>Refresh</ActionButton>} />{error && <Notice>{error}</Notice>}{!data && !error ? <Loading text="Loading dashboard…" /> : <View style={uiStyles.metricGrid}>{metrics.map(([label, value]) => <View key={String(label)} style={uiStyles.metric}><Text style={uiStyles.metricValue}>{String(value ?? 0)}</Text><Text style={uiStyles.metricLabel}>{label}</Text></View>)}</View>}</View>;
}

const emptyAccount = { name: '', email: '', password: '', password_confirmation: '' };

function AccountsScreen() {
  const [role, setRole] = useState<'farmer' | 'agricultural_expert'>('farmer');
  const [items, setItems] = useState<ManagedUser[]>([]); const [query, setQuery] = useState(''); const [search, setSearch] = useState('');
  const [editing, setEditing] = useState<ManagedUser | null>(null); const [form, setForm] = useState(emptyAccount);
  const [modal, setModal] = useState(false); const [deleting, setDeleting] = useState<ManagedUser | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const reviewer = role === 'agricultural_expert'; const endpoint = reviewer ? 'experts' : 'farmers'; const singular = reviewer ? 'Agricultural Reviewer' : 'Farmer';
  const load = useCallback(async () => { setLoading(true); try { const payload = await api<{ items: ManagedUser[] }>(`/admin/${endpoint}?per_page=50${search ? `&search=${encodeURIComponent(search)}` : ''}`); setItems(payload.data.items); setError(''); } catch (e) { setError(messageOf(e)); } finally { setLoading(false); } }, [endpoint, search]);
  useEffect(() => { load(); }, [load]);
  const openCreate = () => { setEditing(null); setForm(emptyAccount); setError(''); setModal(true); };
  const openEdit = (item: ManagedUser) => { setEditing(item); setForm({ name: item.name, email: item.email, password: '', password_confirmation: '' }); setError(''); setModal(true); };
  const submit = async () => { if (!form.name.trim() || !form.email.trim() || (!editing && !form.password)) { setError('Name, email, and a password of at least 8 characters are required for new accounts.'); return; } setBusy(true); const body: Record<string, string> = { ...form, role }; if (editing && !body.password) { delete body.password; delete body.password_confirmation; } try { await api(`/admin/${endpoint}${editing ? `/${editing.id}` : ''}`, { method: editing ? 'PUT' : 'POST', body: JSON.stringify(body) }); const wasEditing = Boolean(editing); setModal(false); setEditing(null); setForm(emptyAccount); setMessage(`${singular} ${wasEditing ? 'updated' : 'created'}.`); setError(''); await load(); } catch (e) { setError(messageOf(e)); } finally { setBusy(false); } };
  const remove = async () => { if (!deleting) return; setBusy(true); try { await api(`/admin/${endpoint}/${deleting.id}`, { method: 'DELETE' }); setDeleting(null); setMessage(`${singular} account deleted.`); setError(''); await load(); } catch (e) { setDeleting(null); setError(messageOf(e)); } finally { setBusy(false); } };
  return <View style={uiStyles.stack}><SectionHeader eyebrow="ADMINISTRATION" title="Accounts" text="Farmers may self-register. Create reviewer accounts only after qualifications are confirmed." action={<ActionButton variant={reviewer ? 'primary' : 'secondary'} icon="add" onPress={openCreate}>Add {reviewer ? 'Reviewer' : 'Farmer'}</ActionButton>} />
    <View style={styles.segment}><Pressable onPress={() => { setRole('farmer'); setSearch(''); setQuery(''); }} style={[styles.segmentItem, !reviewer && styles.segmentActive]}><Text style={[styles.segmentText, !reviewer && styles.segmentTextActive]}>Farmers</Text></Pressable><Pressable onPress={() => { setRole('agricultural_expert'); setSearch(''); setQuery(''); }} style={[styles.segmentItem, reviewer && styles.segmentActive]}><Text style={[styles.segmentText, reviewer && styles.segmentTextActive]}>Reviewers</Text></Pressable></View>
    <View style={uiStyles.inputRow}><View style={uiStyles.searchField}><Field label={`Search ${reviewer ? 'reviewers' : 'farmers'}`} value={query} onChangeText={setQuery} returnKeyType="search" onSubmitEditing={() => setSearch(query.trim())} /></View><ActionButton variant="secondary" icon="search" onPress={() => setSearch(query.trim())}>Search</ActionButton></View>
    {message && <Notice tone="success">{message}</Notice>}{error && <Notice>{error}</Notice>}{loading ? <Loading /> : items.length ? items.map((item) => <View key={item.id} style={uiStyles.card}><View style={uiStyles.rowBetween}><View style={uiStyles.flex}><Text style={uiStyles.cardTitle}>{item.name}</Text><Text style={uiStyles.cardMeta}>{item.email}</Text></View><Text style={uiStyles.pill}>{reviewer ? 'Reviewer' : `${item.diagnoses_count ?? 0} diagnoses`}</Text></View><Text style={uiStyles.cardMeta}>Joined {formatDate(item.created_at)} · {formatDate(item.last_activity_at, true)}</Text><View style={uiStyles.actions}><ActionButton variant="secondary" icon="create-outline" onPress={() => openEdit(item)}>Edit</ActionButton><ActionButton variant="ghost" icon="trash-outline" onPress={() => setDeleting(item)}>Delete</ActionButton></View></View>) : <Empty title={`No ${reviewer ? 'reviewers' : 'farmers'} found`} text={search ? 'Try a different search.' : 'New accounts will appear here.'} />}
    <ModalSheet visible={modal} title={editing ? `Edit ${singular}` : `Add ${singular}`} description={reviewer ? 'Reviewer access is for qualified plant-health personnel.' : 'Assisted onboarding is optional; farmers may register themselves.'} onClose={() => { if (!busy) setModal(false); }}><Field label="Name" value={form.name} onChangeText={(name) => setForm({ ...form, name })} autoCapitalize="words" /><Field label="Email" value={form.email} onChangeText={(email) => setForm({ ...form, email })} keyboardType="email-address" autoCapitalize="none" /><Field label={editing ? 'New password (optional)' : 'Password'} value={form.password} onChangeText={(password) => setForm({ ...form, password })} secureTextEntry /><Field label="Confirm password" value={form.password_confirmation} onChangeText={(password_confirmation) => setForm({ ...form, password_confirmation })} secureTextEntry />{error && <Notice>{error}</Notice>}<View style={uiStyles.actions}><ActionButton variant="secondary" disabled={busy} onPress={() => setModal(false)}>Cancel</ActionButton><ActionButton disabled={busy} onPress={submit}>{busy ? 'Saving…' : editing ? 'Save changes' : `Add ${singular}`}</ActionButton></View></ModalSheet>
    <ConfirmSheet visible={Boolean(deleting)} title={`Delete ${singular}?`} text={reviewer ? `Completed reviews by ${deleting?.name || 'this reviewer'} remain as audit records.` : `Deleting ${deleting?.name || 'this farmer'} also deletes their diagnosis records.`} confirmLabel={`Delete ${singular}`} busy={busy} onCancel={() => setDeleting(null)} onConfirm={remove} />
  </View>;
}

function DiagnosesScreen() {
  const [items, setItems] = useState<Diagnosis[]>([]); const [classFilter, setClassFilter] = useState(''); const [sourceFilter, setSourceFilter] = useState('');
  const [selected, setSelected] = useState<Diagnosis | null>(null); const [deleting, setDeleting] = useState<Diagnosis | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const load = useCallback(async () => { setLoading(true); const params = new URLSearchParams({ per_page: '50' }); if (classFilter) params.set('class', classFilter); if (sourceFilter) params.set('source', sourceFilter); try { const payload = await api<{ items: Diagnosis[] }>(`/admin/diagnoses?${params.toString()}`); setItems(payload.data.items); setError(''); } catch (e) { setError(messageOf(e)); } finally { setLoading(false); } }, [classFilter, sourceFilter]);
  useEffect(() => { load(); }, [load]);
  const inspect = async (item: Diagnosis) => { try { const payload = await api<Diagnosis>(`/admin/diagnoses/${item.id}`); setSelected(payload.data); setError(''); } catch (e) { setError(messageOf(e)); } };
  const remove = async () => { if (!deleting) return; setBusy(true); try { await api(`/admin/diagnoses/${deleting.id}`, { method: 'DELETE' }); setDeleting(null); setSelected(null); setMessage('Diagnosis record deleted.'); await load(); } catch (e) { setDeleting(null); setError(messageOf(e)); } finally { setBusy(false); } };
  return <View style={uiStyles.stack}><SectionHeader eyebrow="SYSTEM RECORDS" title="Diagnoses" text="Saved server records are read-only except for deletion. Local offline scans are not automatically uploaded." />
    <Choice label="Class filter" value={classFilter} options={['', ...CLASS_KEYS]} emptyLabel="All classes" onChange={setClassFilter} /><Choice label="Source filter" value={sourceFilter} options={['', 'mobile', 'web']} emptyLabel="All sources" onChange={setSourceFilter} />
    {message && <Notice tone="success">{message}</Notice>}{error && <Notice>{error}</Notice>}{loading ? <Loading /> : items.length ? items.map((item) => <Pressable key={item.id} accessibilityRole="button" onPress={() => inspect(item)} style={uiStyles.card}><View style={uiStyles.row}>{item.image_url ? <Image source={authenticatedImageSource(item.image_url)} style={styles.thumb} /> : <View style={styles.thumbPlaceholder}><Ionicons name="leaf-outline" size={23} color={palette.green} /></View>}<View style={uiStyles.flex}><Text style={uiStyles.cardTitle}>{item.disease?.name || titleCase(item.predicted_class)}</Text><Text style={uiStyles.cardMeta}>{item.user?.name || 'Unknown farmer'} · {formatDate(item.diagnosed_at, true)}</Text><Text style={uiStyles.cardMeta}>{Number(item.confidence).toFixed(1)}% confidence · {titleCase(item.source)}</Text></View><Ionicons name="chevron-forward" size={20} color={palette.muted} /></View></Pressable>) : <Empty title="No diagnoses found" text="Saved diagnoses matching these filters will appear here." />}
    <ModalSheet visible={Boolean(selected)} title="Diagnosis details" description="Original model output and stored metadata." onClose={() => setSelected(null)}>{selected && <><View style={uiStyles.card}>{selected.image_url && <Image source={authenticatedImageSource(selected.image_url)} style={styles.detailImage} />}<Text style={uiStyles.cardTitle}>{selected.disease?.name || titleCase(selected.predicted_class)}</Text>{[['Confidence', `${Number(selected.confidence).toFixed(1)}%`], ['Farmer', selected.user?.name || 'Unknown'], ['Source', titleCase(selected.source)], ['Diagnosed', formatDate(selected.diagnosed_at, true)], ['Model', selected.model_version || 'Not recorded'], ['Sync', titleCase(selected.sync_status)]].map(([label, value]) => <View key={label} style={uiStyles.rowBetween}><Text style={uiStyles.cardMeta}>{label}</Text><Text style={styles.detailValue}>{value}</Text></View>)}{selected.farmer_notes && <Text style={uiStyles.cardMeta}>Farmer notes: {selected.farmer_notes}</Text>}</View><ActionButton variant="danger" icon="trash-outline" onPress={() => setDeleting(selected)}>Delete diagnosis</ActionButton></>}</ModalSheet>
    <ConfirmSheet visible={Boolean(deleting)} title="Delete diagnosis?" text="This permanently removes the saved server record. It does not affect local offline classification." confirmLabel="Delete diagnosis" busy={busy} onCancel={() => setDeleting(null)} onConfirm={remove} />
  </View>;
}

const emptyDisease = { slug: '', model_class_key: '', name: '', scientific_name: '', causal_agent: '', pathogen_type: '', short_description: '', farmer_summary: '', curative_status: 'unclear_evidence', evidence_level: 'limited', image_only_limitations: '', professional_referral: '', prevention: '' };
type DiseaseForm = typeof emptyDisease;

function DiseasesScreen() {
  const [items, setItems] = useState<DiseaseRecord[]>([]); const [classes, setClasses] = useState<string[]>([]); const [contentStatus, setContentStatus] = useState('');
  const [form, setForm] = useState<DiseaseForm>(emptyDisease); const [editing, setEditing] = useState<DiseaseRecord | null>(null); const [modal, setModal] = useState(false); const [selected, setSelected] = useState<DiseaseDetail | null>(null); const [archiving, setArchiving] = useState<DiseaseRecord | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const load = useCallback(async () => { setLoading(true); try { const [records, system] = await Promise.all([api<DiseaseRecord[]>('/admin/diseases'), api<Record<string, any>>('/admin/system')]); setItems(records.data); const serverClasses = Array.isArray(system.data.classes) ? system.data.classes.filter((item): item is string => typeof item === 'string') : []; setClasses(serverClasses); setContentStatus(String(system.data.disease_content_status || '')); setError(''); } catch (e) { setError(messageOf(e)); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const available = classes.filter((key) => !items.some((item) => item.model_class_key === key));
  const openCreate = () => { const key = available[0] || ''; setEditing(null); setForm({ ...emptyDisease, slug: key, model_class_key: key }); setError(''); setModal(true); };
  const openEdit = (item: DiseaseRecord) => { setEditing(item); setForm({ ...emptyDisease, ...item, farmer_summary: item.farmer_summary || item.description || '', scientific_name: item.scientific_name || '', causal_agent: item.causal_agent || '', pathogen_type: item.pathogen_type || '', short_description: item.short_description || '', image_only_limitations: item.image_only_limitations || '', professional_referral: item.professional_referral || '', prevention: item.prevention || '' }); setError(''); setModal(true); };
  const submit = async () => { if (!form.model_class_key || !form.name.trim()) { setError('Choose a validated class and enter the accepted disease name.'); return; } setBusy(true); try { await api(`/admin/diseases${editing ? `/${editing.id}` : ''}`, { method: editing ? 'PUT' : 'POST', body: JSON.stringify({ ...form, alternative_names: editing?.alternative_names || [] }) }); const wasEditing = Boolean(editing); setModal(false); setEditing(null); setMessage(wasEditing ? 'Disease content saved and returned for review when required.' : 'Draft disease record created.'); setError(''); await load(); } catch (e) { setError(messageOf(e)); } finally { setBusy(false); } };
  const inspect = async (item: DiseaseRecord) => { try { const payload = await api<DiseaseDetail>(`/admin/diseases/${item.id}`); setSelected(payload.data); } catch (e) { setError(messageOf(e)); } };
  const submitForReview = async (item: DiseaseRecord) => { try { await api(`/admin/diseases/${item.id}/status`, { method: 'PUT', body: JSON.stringify({ status: 'researched' }) }); setMessage(`${item.name} submitted for agricultural review.`); await load(); } catch (e) { setError(messageOf(e)); } };
  const archive = async () => { if (!archiving) return; setBusy(true); try { await api(`/admin/diseases/${archiving.id}`, { method: 'DELETE' }); setArchiving(null); setSelected(null); setMessage('Disease knowledge record archived.'); await load(); } catch (e) { setArchiving(null); setError(messageOf(e)); } finally { setBusy(false); } };
  return <View style={uiStyles.stack}><SectionHeader eyebrow="ADMIN / RESEARCH" title="Disease knowledge" text="Maintain one governed record per validated model class." action={<ActionButton icon="add" disabled={!available.length} onPress={openCreate}>Add missing class</ActionButton>} />{contentStatus ? <Notice tone="warning">{contentStatus}</Notice> : null}{classes.length > 0 && !available.length && <Notice tone="success">All {classes.length} validated classes already have records. Edit an existing record instead of adding an unsupported class.</Notice>}{message && <Notice tone="success">{message}</Notice>}{error && <Notice>{error}</Notice>}
    {loading ? <Loading /> : items.length ? items.map((item) => <View key={item.id} style={uiStyles.card}><View style={uiStyles.rowBetween}><View style={uiStyles.flex}><Text style={uiStyles.cardTitle}>{item.name}</Text><Text style={uiStyles.cardMeta}>{item.model_class_key} · {item.causal_agent || 'Causal agent pending'}</Text></View><Text style={uiStyles.pill}>{titleCase(item.verification_status)}</Text></View><Text style={uiStyles.cardMeta}>{titleCase(item.evidence_level)} evidence · {item.sources_count ?? 0} sources · reviewed {formatDate(item.last_reviewed_at)}</Text><View style={uiStyles.actions}><ActionButton variant="secondary" onPress={() => inspect(item)}>View</ActionButton><ActionButton variant="secondary" onPress={() => openEdit(item)}>Edit</ActionButton>{item.verification_status === 'draft' && <ActionButton variant="ghost" onPress={() => submitForReview(item)}>Submit</ActionButton>}<ActionButton variant="ghost" onPress={() => setArchiving(item)}>Archive</ActionButton></View></View>) : <Empty title="Disease content pending" text={classes.length ? 'Create only records for missing validated classes.' : 'The validated label map is unavailable, so records cannot be created safely.'} />}
    <ModalSheet visible={modal} title={editing ? 'Edit disease record' : 'Add missing class record'} description="Saving researched content may return it for agricultural review." onClose={() => { if (!busy) setModal(false); }}><Choice label="Validated model class" value={form.model_class_key} options={editing ? classes : available} onChange={(model_class_key) => setForm({ ...form, model_class_key, slug: model_class_key })} /><Field label="Accepted disease name" value={form.name} onChangeText={(name) => setForm({ ...form, name })} /><Field label="Scientific name" value={form.scientific_name} onChangeText={(scientific_name) => setForm({ ...form, scientific_name })} /><Field label="Causal agent" value={form.causal_agent} onChangeText={(causal_agent) => setForm({ ...form, causal_agent })} /><Choice label="Pathogen type" value={form.pathogen_type} options={['', 'fungus', 'bacterium', 'virus', 'other']} emptyLabel="Not established" onChange={(pathogen_type) => setForm({ ...form, pathogen_type })} /><Choice label="Curative status" value={form.curative_status} options={['unclear_evidence', 'manageable_not_curable', 'no_known_cure', 'curative_treatment_available']} onChange={(curative_status) => setForm({ ...form, curative_status })} /><Choice label="Evidence level" value={form.evidence_level} options={['limited', 'moderate', 'high']} onChange={(evidence_level) => setForm({ ...form, evidence_level })} />{([['short_description', 'Short description'], ['farmer_summary', 'Farmer summary'], ['prevention', 'How to help prevent spread'], ['professional_referral', 'When to seek expert help'], ['image_only_limitations', 'Image-only limitations']] as const).map(([key, label]) => <Field key={key} label={label} multiline value={form[key]} onChangeText={(value) => setForm({ ...form, [key]: value })} />)}{error && <Notice>{error}</Notice>}<View style={uiStyles.actions}><ActionButton variant="secondary" disabled={busy} onPress={() => setModal(false)}>Cancel</ActionButton><ActionButton disabled={busy} onPress={submit}>{busy ? 'Saving…' : editing ? 'Save changes' : 'Create draft'}</ActionButton></View></ModalSheet>
    <ModalSheet visible={Boolean(selected)} title={selected?.disease.name || 'Disease details'} description="Research and farmer-facing content for this validated class." onClose={() => setSelected(null)}>{selected && <><View style={uiStyles.card}><Text style={styles.detailLabel}>FARMER CONTENT</Text><Text style={styles.detailBody}>{selected.disease.description || 'Insufficient verified evidence available.'}</Text><Text style={styles.detailLabel}>MANAGEMENT AND PREVENTION</Text><Text style={styles.detailBody}>{selected.disease.management || 'Insufficient verified evidence available.'}</Text><Text style={styles.detailLabel}>IMAGE-ONLY LIMITATIONS</Text><Text style={styles.detailBody}>{selected.disease.image_only_limitations || 'Not yet documented.'}</Text></View><View style={uiStyles.card}>{[['Model class', selected.disease.model_class_key], ['Scientific name', selected.disease.scientific_name || 'Pending'], ['Causal agent', selected.disease.causal_agent || 'Pending'], ['Evidence', titleCase(selected.disease.evidence_level)], ['Sources', String(selected.disease.sources_count ?? 0)]].map(([label, value]) => <View key={label} style={uiStyles.rowBetween}><Text style={uiStyles.cardMeta}>{label}</Text><Text style={styles.detailValue}>{value}</Text></View>)}</View>{selected.regulatory_recheck_required && <Notice>Regulatory re-check required.</Notice>}{selected.evidence?.map((claim) => <View key={claim.id} style={uiStyles.card}><Text style={uiStyles.cardTitle}>{titleCase(claim.claim_type)} · {titleCase(claim.evidence_strength)}</Text><Text style={uiStyles.cardMeta}>{claim.claim_text}</Text></View>)}<View style={uiStyles.actions}><ActionButton variant="secondary" onPress={() => { const record = selected.disease; setSelected(null); openEdit(record); }}>Edit content</ActionButton><ActionButton variant="danger" onPress={() => setArchiving(selected.disease)}>Archive</ActionButton></View></>}</ModalSheet>
    <ConfirmSheet visible={Boolean(archiving)} title="Archive disease record?" text={`${archiving?.name || 'This record'} will no longer be active. This uses the server's archive operation.`} confirmLabel="Archive record" busy={busy} onCancel={() => setArchiving(null)} onConfirm={archive} />
  </View>;
}

const emptySource = { title: '', authors: '', year: '', journal_or_institution: '', source_type: 'peer_reviewed_article', doi: '', reference_url: '', country_or_region: '', peer_reviewed: true, philippines_specific: false, notes: '' };
type SourceForm = typeof emptySource;
const sourceTypes = ['peer_reviewed_article', 'systematic_review', 'review_article', 'government_guideline', 'FAO_guideline', 'university_extension', 'regulatory_document', 'academic_book_chapter', 'research_institute'] as const;

function SourcesScreen() {
  const [items, setItems] = useState<ResearchSource[]>([]); const [tab, setTab] = useState<'sources' | 'claims'>('sources'); const [query, setQuery] = useState(''); const [search, setSearch] = useState(''); const [form, setForm] = useState<SourceForm>(emptySource); const [editing, setEditing] = useState<ResearchSource | null>(null); const [modal, setModal] = useState(false); const [deleting, setDeleting] = useState<ResearchSource | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const load = useCallback(async () => { setLoading(true); try { const payload = await api<ResearchSource[]>(`/admin/research-sources${search ? `?search=${encodeURIComponent(search)}` : ''}`); setItems(payload.data); setError(''); } catch (e) { setError(messageOf(e)); } finally { setLoading(false); } }, [search]);
  useEffect(() => { load(); }, [load]);
  const claims = useMemo(() => items.flatMap((source) => (source.evidence || []).map((claim) => ({ ...claim, source }))), [items]);
  const openCreate = () => { setEditing(null); setForm(emptySource); setError(''); setModal(true); };
  const openEdit = (item: ResearchSource) => { setEditing(item); setForm({ ...emptySource, ...item, year: item.year ? String(item.year) : '', doi: item.doi || '', reference_url: item.reference_url || '', country_or_region: item.country_or_region || '', notes: item.notes || '' }); setError(''); setModal(true); };
  const submit = async () => { if (!form.title.trim() || !form.authors.trim() || !form.journal_or_institution.trim()) { setError('Title, authors, and journal or institution are required.'); return; } setBusy(true); const body = { ...form, year: form.year ? Number(form.year) : null, doi: form.doi || null, reference_url: form.reference_url || null }; try { await api(`/admin/research-sources${editing ? `/${editing.id}` : ''}`, { method: editing ? 'PUT' : 'POST', body: JSON.stringify(body) }); const wasEditing = Boolean(editing); setModal(false); setEditing(null); setMessage(wasEditing ? 'Source updated; affected content was returned for review.' : 'Research source added.'); setError(''); await load(); } catch (e) { setError(messageOf(e)); } finally { setBusy(false); } };
  const remove = async () => { if (!deleting) return; setBusy(true); try { await api(`/admin/research-sources/${deleting.id}`, { method: 'DELETE' }); setDeleting(null); setMessage('Unused research source deleted.'); await load(); } catch (e) { setDeleting(null); setError(messageOf(e)); } finally { setBusy(false); } };
  return <View style={uiStyles.stack}><SectionHeader eyebrow="ADMIN / RESEARCH" title="Research sources" text="Maintain traceable evidence and inspect the disease claims using each source." action={<ActionButton icon="add" onPress={openCreate}>Add source</ActionButton>} />
    <View style={styles.segment}><Pressable onPress={() => setTab('sources')} style={[styles.segmentItem, tab === 'sources' && styles.segmentActive]}><Text style={[styles.segmentText, tab === 'sources' && styles.segmentTextActive]}>Sources</Text></Pressable><Pressable onPress={() => setTab('claims')} style={[styles.segmentItem, tab === 'claims' && styles.segmentActive]}><Text style={[styles.segmentText, tab === 'claims' && styles.segmentTextActive]}>Claims ({claims.length})</Text></Pressable></View>
    <View style={uiStyles.inputRow}><View style={uiStyles.searchField}><Field label="Search references" value={query} onChangeText={setQuery} returnKeyType="search" onSubmitEditing={() => setSearch(query.trim())} /></View><ActionButton variant="secondary" icon="search" onPress={() => setSearch(query.trim())}>Search</ActionButton></View>
    {message && <Notice tone="success">{message}</Notice>}{error && <Notice>{error}</Notice>}{loading ? <Loading /> : tab === 'sources' ? (items.length ? items.map((item) => <View key={item.id} style={uiStyles.card}><Text style={uiStyles.cardTitle}>{item.authors} ({item.year || 'n.d.'}). {item.title}.</Text><Text style={uiStyles.cardMeta}>{item.journal_or_institution}{item.doi ? ` · DOI: ${item.doi}` : ''}</Text><View style={uiStyles.row}><Text style={uiStyles.pill}>{titleCase(item.source_type)}</Text><Text style={uiStyles.cardMeta}>{item.evidence_count ?? 0} mapped claims</Text></View><Text style={uiStyles.cardMeta}>{item.peer_reviewed ? 'Peer reviewed' : 'Authoritative'}{item.philippines_specific ? ' · Philippines-specific' : ''}</Text><View style={uiStyles.actions}><ActionButton variant="secondary" onPress={() => openEdit(item)}>Edit</ActionButton>{item.evidence_count ? <Text style={styles.inUse}>In use — remove mappings before deletion</Text> : <ActionButton variant="ghost" onPress={() => setDeleting(item)}>Delete</ActionButton>}</View></View>) : <Empty title="No research sources found" text={search ? 'Try a different search.' : 'Add only sources checked against the original publication or authority.'} />) : (claims.length ? claims.map((claim) => <View key={claim.id} style={uiStyles.card}><Text style={uiStyles.cardTitle}>{titleCase(claim.claim_type)} · {titleCase(claim.evidence_strength)}</Text><Text style={styles.detailBody}>{claim.claim_text}</Text><Text style={uiStyles.cardMeta}>{claim.disease?.name || 'Disease record'} — {claim.source.authors} ({claim.source.year || 'n.d.'}).</Text></View>) : <Empty title="No mapped claims found" text="Claims appear after a source is mapped to disease knowledge." />)}
    <ModalSheet visible={modal} title={editing ? 'Edit research source' : 'Add research source'} description={editing ? 'Changing a source returns affected verified content for re-review.' : 'Record only sources checked against the original publication or authority.'} onClose={() => { if (!busy) setModal(false); }}><Field label="Title" value={form.title} onChangeText={(title) => setForm({ ...form, title })} /><Field label="Authors" value={form.authors} onChangeText={(authors) => setForm({ ...form, authors })} /><Field label="Publication year" value={form.year} onChangeText={(year) => setForm({ ...form, year })} keyboardType="number-pad" /><Field label="Journal or institution" value={form.journal_or_institution} onChangeText={(journal_or_institution) => setForm({ ...form, journal_or_institution })} /><Choice label="Source type" value={form.source_type} options={sourceTypes} onChange={(source_type) => setForm({ ...form, source_type })} /><Field label="DOI (optional)" value={form.doi} onChangeText={(doi) => setForm({ ...form, doi })} autoCapitalize="none" /><Field label="Reference URL" value={form.reference_url} onChangeText={(reference_url) => setForm({ ...form, reference_url })} keyboardType="url" autoCapitalize="none" /><Field label="Country or region" value={form.country_or_region} onChangeText={(country_or_region) => setForm({ ...form, country_or_region })} /><Field label="Notes" multiline value={form.notes} onChangeText={(notes) => setForm({ ...form, notes })} /><Toggle label="Peer reviewed" value={form.peer_reviewed} onChange={(peer_reviewed) => setForm({ ...form, peer_reviewed })} /><Toggle label="Philippines-specific" value={form.philippines_specific} onChange={(philippines_specific) => setForm({ ...form, philippines_specific })} />{error && <Notice>{error}</Notice>}<View style={uiStyles.actions}><ActionButton variant="secondary" disabled={busy} onPress={() => setModal(false)}>Cancel</ActionButton><ActionButton disabled={busy} onPress={submit}>{busy ? 'Saving…' : editing ? 'Save and trigger re-review' : 'Add source'}</ActionButton></View></ModalSheet>
    <ConfirmSheet visible={Boolean(deleting)} title="Delete unused source?" text={`Delete ${deleting?.title || 'this source'}. Sources with mapped claims cannot be deleted.`} confirmLabel="Delete source" busy={busy} onCancel={() => setDeleting(null)} onConfirm={remove} />
  </View>;
}

const styles = StyleSheet.create({
  workspace: { gap: 16 }, adminHeader: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: palette.card, borderRadius: 18, borderWidth: 1, borderColor: palette.border, padding: 15 }, kicker: { color: palette.green, fontSize: 10, fontWeight: '900', letterSpacing: 1.1 }, adminName: { color: palette.ink, fontSize: 18, fontWeight: '900' }, adminEmail: { color: palette.muted, fontSize: 12 }, signOut: { width: 44, height: 44, borderRadius: 14, backgroundColor: palette.greenSoft, alignItems: 'center', justifyContent: 'center' },
  nav: { gap: 8, paddingRight: 4 }, navItem: { height: 40, borderRadius: 999, borderWidth: 1, borderColor: palette.border, paddingHorizontal: 13, flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#fff' }, navItemActive: { backgroundColor: palette.green, borderColor: palette.green }, navText: { color: palette.green, fontSize: 12, fontWeight: '800' }, navTextActive: { color: '#fff' },
  segment: { flexDirection: 'row', padding: 4, backgroundColor: '#e5ece7', borderRadius: 15 }, segmentItem: { flex: 1, minHeight: 41, borderRadius: 11, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 7 }, segmentActive: { backgroundColor: '#fff' }, segmentText: { color: palette.muted, fontSize: 13, fontWeight: '800', textAlign: 'center' }, segmentTextActive: { color: palette.green },
  thumb: { width: 66, height: 66, borderRadius: 13, backgroundColor: palette.greenSoft }, thumbPlaceholder: { width: 66, height: 66, borderRadius: 13, backgroundColor: palette.greenSoft, alignItems: 'center', justifyContent: 'center' }, detailImage: { width: '100%', aspectRatio: 1.25, borderRadius: 15, backgroundColor: palette.greenSoft, marginBottom: 5 }, detailValue: { flexShrink: 1, color: palette.ink, fontSize: 13, fontWeight: '700', textAlign: 'right' }, detailLabel: { color: palette.green, fontSize: 10, fontWeight: '900', letterSpacing: 1 }, detailBody: { color: palette.ink, fontSize: 14, lineHeight: 21 }, inUse: { color: palette.muted, fontSize: 12, alignSelf: 'center', flexShrink: 1 },
});
